### ISSUE TITLE
the impossibility of minimum spanning trees

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/flipper#3]
@mdsumner A random Q for ya, because you were randomly trying this 13 years ago (in [this `r-help`](https://stat.ethz.ch/pipermail/r-help/2004-August/056177.html)):

We're making a package to aid package discovery on CRAN, for which I had envisioned constructing a minimal spanning tree of inter-relationships between all packages. The matrix of relationships is no prob - currently just over 11,000-by-11,000. But constructing any kind of MST of this size seems impossible. Can you perchance give any tips you might have picked up in the intervening 13 years?

(And i've tried `igraph::mst` - useless; `ade4::mstree`, `ape::mst`, and `vegan::spantree`. It's a completely dense graph, but even then `O(m log n) ~ 121 million * 10` equals just over a billion operations, which ought to be possible, just not in memory. What is needed here is an algorithm that dumps each step to disk and re-loads the final tree into memory at the end, which would be trivial, yet  there doesn't seem to be such a thing.)

Just a simple :-1: if you've no idea, and i'll move onto plan B.

**Comment by mdsumner** [comment]
not off top of head 👎 (but I'll ask local experts)

**Comment by mdsumner** [comment]
We are talking about Prim's algorithm ...

**Comment by mpadge** [comment]
nah, there's actually a better one for mega-dense matrices using ["Fibonacci heaps"](http://dl.acm.org/citation.cfm?doid=28869.28874), but i don't think that's been implemented at all in R. Plan B is maybe better anyway, just has larger storage requirements that I have to find clever ways around. Thanks anyway!

**Comment by mdsumner** [comment]
That is in datastructures yeah? I appreciate the banter anyway, your theoretical insights mapped to my code aspirations :)
